### ISSUE TITLE
Setup repo and add files and folders

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/superhero-assembly#1]
### Tasks

- [x] add html, css and js files and folders
- [x] import bootstrap
- [x] import jQuery
- [x] import fontawesome
- [x] import google font family
- [x] import colour scheme
