### ISSUE TITLE
Build assemble page for no search results

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/superhero-assembly#4]
### Tasks

- [x] use navigation bar from index.html and set Assemble to active
- [x] add search form with input field (placeholder "Enter superhero name") and a "Search" button
- [x] add a no results component to display "No results found"

### Designs

![image](https://user-images.githubusercontent.com/10376859/137583333-f9f3cb73-ee9b-4d0d-a3fc-84bf880852bd.png)
