### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/superhero-assembly#6]
### Tasks

- [x] user should be able to enter a superhero name and click on search
- [x] when search is valid then make an API request and retrieve data
- [x] console log the data from API
- [x] add validation to form, user should not be able to submit empty input value
- [x] if invalid then show error on page
